package front.vista.simulacion;

import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nico Ferraro
 */
public class PopUpPuntosMedios extends javax.swing.JFrame {
    
    private JTable tabla;
    private PuntosTableModel tableModel;
    private HashMap<Integer, Float> ptosMedios;
    
    public PopUpPuntosMedios() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tabla de promedio de puntos por numero de bolos tirados en primer tiro");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setearTabla();
        ptosMedios = new HashMap<>();
    }
    
    private class PuntosTableModel extends DefaultTableModel
    {
        @Override
        public Object getValueAt(int row, int col) 
        {
            
            Object value = null;
            if (row >= 0 && ptosMedios != null)
            {
                switch (col)
                {
                    case 0:
                    {
                        value = row+3;
                        break;
                    }
                    case 1: 
                    {
                        value = ptosMedios.get(row+3);
                        if (value instanceof Double && ((Double)value) == Double.MAX_VALUE)
                        {
                            value = (double) 0;
                        }
                        break;
                    }
                }
            }
            return value;
        }
            
        @Override
        public int getRowCount() {
            return ptosMedios != null ? ptosMedios.size() : 0;
        }
        
        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public String getColumnName(int columnIndex) {
            String colName ="";
            switch (columnIndex)
            {
                case 0:
                {
                    colName = "Bolos Primer Tiro";
                    break;
                }
                case 1:
                {
                    colName = "Cantidad Puntos medio";
                    break;
                }
            }
            return colName;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch (columnIndex)
            {
                case 0:
                {
                    return Integer.class;
                }
                case 1:
                {
                    return Double.class;
                }
            }
            return Class.class;
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    }
    
    private void setearTabla() {
        tabla = new JTable();
        scpPtosMedios.setViewportView(tabla);
        tableModel = new PuntosTableModel();
        tabla.setModel(tableModel);
    }
    
    void setPuntos(HashMap<Integer, Float> hash) {
        this.ptosMedios = hash;
        tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpPtosMedios = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpPtosMedios, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpPtosMedios, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scpPtosMedios;
    // End of variables declaration//GEN-END:variables
}
