package front.vista.simulacion;

import front.vista.simulacion.exception.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import objects.Calculator;
import objects.Controller;

public class VentanaPrincipal extends javax.swing.JFrame {
    Controller controller;
    int cantRondas = 0; 
    int puntaje10PrimerTiro = 0; 
    int puntaje10SegundoTiro = 0; 
    int valorSuperar = 0;
    Calculator calculator = new Calculator();
    boolean valuesSet = false;
    private final DecimalFormat df = new DecimalFormat("0.00");
    private final int COL_PROB = 1;
    private final int COL_P_ACUM = 2;
    private final List<JTable> listaTablas = new ArrayList<>();
    private final List<Float> listaProbDefault = new ArrayList<>();
    private int _10primerTiroDefault;
    private int _10seguntoTiroDefault;
    private int _rondasDefault;
    private int _valorSuperarDefault;
    private final PopUpPuntosMedios popUpPuntos;

    
    public void setEspecificos(int cantRondas, int puntosPrimerTiro, int puntosSegundoTiro, int valorASuperar) 
    {
        this.cantRondas = cantRondas;
        this.puntaje10PrimerTiro = puntosPrimerTiro;
        this.puntaje10SegundoTiro = puntosSegundoTiro;
        this.valorSuperar = valorASuperar;
    }
    
    public VentanaPrincipal(Controller cont) {
        controller = cont;
        initComponents();
        crearListaDeTablas();
        prepararValoresPorDefault();
        popUpPuntos = new PopUpPuntosMedios();
        this.setTitle("Trabajo Practico Final Simulacion 2021 - Ferraro, Pablo Nicolás");
        btn_mostrarPtos.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        scpSimulacion = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        _scpMontecarlo = new javax.swing.JScrollPane();
        _tblMontecarlo = new javax.swing.JTable();
        _lblTituloMontecarlo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrimerTiro = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDespues9 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDespues5 = new javax.swing.JTable();
        _lblPrimerTiro = new javax.swing.JLabel();
        _lblDespues8 = new javax.swing.JLabel();
        lblDespues9 = new javax.swing.JLabel();
        _lbl7antes = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        _lblDespues9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDespues4 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblDespues3 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDespues8 = new javax.swing.JTable();
        lblDespues10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblDespues7 = new javax.swing.JTable();
        _lbl7antes1 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblDespues6 = new javax.swing.JTable();
        _lbl7antes2 = new javax.swing.JLabel();
        _btnSimular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        _txt10PrimerTiro = new javax.swing.JTextField();
        _txt10SegundoTiro = new javax.swing.JTextField();
        _txtRondas = new javax.swing.JTextField();
        _txtCantSim = new javax.swing.JTextField();
        _txtDesde = new javax.swing.JTextField();
        _txtHasta = new javax.swing.JTextField();
        _txtValorSuperar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        _btnLimpiar = new javax.swing.JButton();
        resultado_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cargarPorDefecto = new javax.swing.JButton();
        btn_mostrarPtos = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Resultados");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP N°4: Montecarlo");

        scpSimulacion.setPreferredSize(new java.awt.Dimension(1193, 472));
        scpSimulacion.setRequestFocusEnabled(false);

        _scpMontecarlo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        _tblMontecarlo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Simulación", "# Ronda", "RND1", "1° Tiro", "RND2", "2° Tiro", "Total Pinos", "Puntos totales", "Puntos acumulados", "Supera? (S|N)", "Acumulador Supera 120"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        _tblMontecarlo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        _tblMontecarlo.getTableHeader().setReorderingAllowed(false);
        _scpMontecarlo.setViewportView(_tblMontecarlo);
        if (_tblMontecarlo.getColumnModel().getColumnCount() > 0) {
            _tblMontecarlo.getColumnModel().getColumn(0).setPreferredWidth(75);
            _tblMontecarlo.getColumnModel().getColumn(0).setMaxWidth(75);
            _tblMontecarlo.getColumnModel().getColumn(1).setPreferredWidth(75);
            _tblMontecarlo.getColumnModel().getColumn(1).setMaxWidth(75);
            _tblMontecarlo.getColumnModel().getColumn(2).setMinWidth(100);
            _tblMontecarlo.getColumnModel().getColumn(3).setMaxWidth(75);
            _tblMontecarlo.getColumnModel().getColumn(4).setMinWidth(100);
            _tblMontecarlo.getColumnModel().getColumn(4).setMaxWidth(100);
            _tblMontecarlo.getColumnModel().getColumn(5).setMaxWidth(75);
            _tblMontecarlo.getColumnModel().getColumn(6).setMinWidth(80);
            _tblMontecarlo.getColumnModel().getColumn(7).setMinWidth(100);
            _tblMontecarlo.getColumnModel().getColumn(8).setMinWidth(100);
            _tblMontecarlo.getColumnModel().getColumn(9).setMinWidth(75);
            _tblMontecarlo.getColumnModel().getColumn(10).setMinWidth(100);
        }

        _lblTituloMontecarlo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lblTituloMontecarlo.setForeground(new java.awt.Color(102, 102, 102));
        _lblTituloMontecarlo.setText("Vector Estado - Montecarlo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(_scpMontecarlo, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(429, 429, 429)
                    .addComponent(_lblTituloMontecarlo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(788, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(_scpMontecarlo, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(214, 214, 214)
                    .addComponent(_lblTituloMontecarlo)
                    .addContainerGap(241, Short.MAX_VALUE)))
        );

        scpSimulacion.addTab("Simulacion", jPanel2);

        tblPrimerTiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(3), null, null},
                { new Integer(4), null, null},
                { new Integer(5), null, null},
                { new Integer(6), null, null},
                { new Integer(7), null, null},
                { new Integer(8), null, null},
                { new Integer(9), null, null},
                { new Integer(10), null, null}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPrimerTiro);

        tblDespues9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0), null, null},
                { new Integer(1), null, null}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDespues9);
        if (tblDespues9.getColumnModel().getColumnCount() > 0) {
            tblDespues9.getColumnModel().getColumn(2).setResizable(false);
        }

        tblDespues5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0), null, null},
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null},
                { new Integer(4), null, null},
                { new Integer(5), null, null}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblDespues5);

        _lblPrimerTiro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lblPrimerTiro.setForeground(new java.awt.Color(102, 102, 102));
        _lblPrimerTiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lblPrimerTiro.setText("Distribución - Cantidad de pinos tirados en el primer tiro");

        _lblDespues8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lblDespues8.setForeground(new java.awt.Color(102, 102, 102));
        _lblDespues8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lblDespues8.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si antes se tiraron 3");

        lblDespues9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDespues9.setForeground(new java.awt.Color(102, 102, 102));
        lblDespues9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDespues9.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si se tiraron 8");

        _lbl7antes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lbl7antes.setForeground(new java.awt.Color(102, 102, 102));
        _lbl7antes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lbl7antes.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si se tiraron 5");

        jLabel13.setText("La probabilidad acumulada se calcula automaticamente al guardar los cambios.");

        _lblDespues9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lblDespues9.setForeground(new java.awt.Color(102, 102, 102));
        _lblDespues9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lblDespues9.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si antes se tiraron 4");

        tblDespues4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0), null, null},
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null},
                { new Integer(4), null, null},
                { new Integer(5), null, null},
                { new Integer(6), null, null}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblDespues4);
        if (tblDespues4.getColumnModel().getColumnCount() > 0) {
            tblDespues4.getColumnModel().getColumn(2).setResizable(false);
        }

        tblDespues3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0), null, null},
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null},
                { new Integer(4), null, null},
                { new Integer(5), null, null},
                { new Integer(6), null, null},
                { new Integer(7), null, null}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblDespues3);
        if (tblDespues3.getColumnModel().getColumnCount() > 0) {
            tblDespues3.getColumnModel().getColumn(2).setResizable(false);
        }

        tblDespues8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0), null, null},
                { new Integer(1), null, null},
                { new Integer(2), null, null}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tblDespues8);

        lblDespues10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDespues10.setForeground(new java.awt.Color(102, 102, 102));
        lblDespues10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDespues10.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si se tiraron 9");

        tblDespues7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0), null, null},
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblDespues7);

        _lbl7antes1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lbl7antes1.setForeground(new java.awt.Color(102, 102, 102));
        _lbl7antes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lbl7antes1.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si se tiraron 6");

        tblDespues6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0), null, null},
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null},
                { new Integer(4), null, null}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tblDespues6);

        _lbl7antes2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lbl7antes2.setForeground(new java.awt.Color(102, 102, 102));
        _lbl7antes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lbl7antes2.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si se tiraron 7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(_lblDespues8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(_lblPrimerTiro))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(_lbl7antes2)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(_lblDespues9)
                                .addComponent(_lbl7antes))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_lbl7antes1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDespues9)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDespues10))))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lblPrimerTiro)
                    .addComponent(_lblDespues9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(_lbl7antes2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(lblDespues9)
                                .addGap(148, 148, 148)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_lbl7antes)
                                .addGap(136, 136, 136)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(_lbl7antes1)
                                    .addComponent(lblDespues10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(_lblDespues8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        scpSimulacion.addTab("Distribuciones de frecuencias", jPanel1);

        _btnSimular.setText("Guardar cambios y simular");
        _btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnSimularActionPerformed(evt);
            }
        });

        jLabel1.setText("Puntaje de 10 pinos en el segundo tiro");

        jLabel2.setText("Puntaje de 10 pinos en el primer tiro");

        jLabel3.setText("Cantidad de rondas a simular");

        jLabel4.setText("Desde");

        jLabel5.setText("Hasta");

        jLabel6.setText("Cantidad de simulaciones");

        jLabel7.setText("Puntaje a superar");

        _btnLimpiar.setText("Limpiar Campos");
        _btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnLimpiarActionPerformed(evt);
            }
        });

        resultado_txt.setEditable(false);
        resultado_txt.setBackground(new java.awt.Color(255, 51, 51));
        resultado_txt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        resultado_txt.setToolTipText("Resultado de simulacion");

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("La probabilidad de que supere es:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        cargarPorDefecto.setText("Cargar valores por defecto");
        cargarPorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarPorDefectoActionPerformed(evt);
            }
        });

        btn_mostrarPtos.setText("Mostrar puntos medios");
        btn_mostrarPtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarPtosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_txtRondas, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(_txt10SegundoTiro, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(_txt10PrimerTiro, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(_txtValorSuperar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(cargarPorDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_mostrarPtos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(resultado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(_txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_txtCantSim, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_btnSimular)))
                        .addGap(9, 9, 9))
                    .addComponent(scpSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(scpSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(_txt10PrimerTiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(_txtCantSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(_btnSimular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_txt10SegundoTiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(_txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(resultado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_txtRondas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(_txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_txtValorSuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(_btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargarPorDefecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_mostrarPtos)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnSimularActionPerformed
        try
        {
            if (!valuesSet)
            {
                //Solo para que valide que este todo
                setCheck();
            }
            DefaultTableModel model = (DefaultTableModel) _tblMontecarlo.getModel();
            model.setRowCount(0);
        
            ingresosValidos();
        }
        catch(InputException invalidInput)
        {
            JOptionPane.showMessageDialog(null, invalidInput.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        calculator.especificoTablas(this, Integer.parseInt(_txtCantSim.getText()), Integer.parseInt(_txtDesde.getText()),
                Integer.parseInt(_txtHasta.getText()), cantRondas, puntaje10PrimerTiro, puntaje10SegundoTiro, valorSuperar);
        popUpPuntos.setPuntos(calculator.getPtosMedios());
        resultado_txt.setText(Double.toString((double)calculator.getCantidadExperimentosValidos()/Double.parseDouble(_txtCantSim.getText())));
        calculator.limpiarValoresGlobales();
        valuesSet = false;
        scpSimulacion.setSelectedIndex(1);
        btn_mostrarPtos.setEnabled(true);
    }//GEN-LAST:event__btnSimularActionPerformed

    private void ingresosValidos() throws InputException
    {
        if (_txtCantSim.getText() == null || "".equals(_txtCantSim.getText()))
        {
            throw new InputException("Ingrese cantidad de Simulaciones");
        }
        
        if (_txtDesde.getText() == null || "".equals(_txtDesde.getText()))
        {
            throw new InputException("Ingrese desde qué simulacion quiere visualizar");
        }
        
        if (_txtHasta.getText() == null || "".equals(_txtHasta.getText()))
        {
            throw new InputException("Ingrese hasta qué simulacion quiere visualizar");
        }
        if (Integer.parseInt(_txtHasta.getText()) <= Integer.parseInt(_txtDesde.getText()))
        {
            throw new InputException("Desde debe ser menor a Hasta");
        }
        if (Integer.parseInt(_txtDesde.getText()) > 500)
        {
            throw new InputException("Desde debe ser menor a 500");
        }
    }
    
   
    private void _btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnLimpiarActionPerformed
        _txt10PrimerTiro.setText("");
        _txt10SegundoTiro.setText("");
        _txtCantSim.setText("");
        _txtDesde.setText("");
        _txtHasta.setText("");
        _txtRondas.setText("");
        _txtValorSuperar.setText("");
        resultado_txt.setText("");
        DefaultTableModel dtm = (DefaultTableModel) _tblMontecarlo.getModel();
        dtm.setRowCount(0);
        limpiarTablas();
        popUpPuntos.setPuntos(null);
        calculator.vaciarMap();
        scpSimulacion.setSelectedIndex(0);
        btn_mostrarPtos.setEnabled(false);
    }//GEN-LAST:event__btnLimpiarActionPerformed

    private void cargarPorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarPorDefectoActionPerformed
        //Popular Tablas (Probabilidades solamente)
        popularTablasPorDefecto();
        //Popular campos requeridos
        popularCamposRequeridosPorDefecto();
        //Llamar funcionalidad que valide input
        /*try
        {
            setCheck();
        }
        catch (InputException invalidInput)
        {
            JOptionPane.showMessageDialog(null, invalidInput.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_cargarPorDefectoActionPerformed

    private void btn_mostrarPtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarPtosActionPerformed
        popUpPuntos.setVisible(true);
    }//GEN-LAST:event_btn_mostrarPtosActionPerformed
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnLimpiar;
    private javax.swing.JButton _btnSimular;
    private javax.swing.JLabel _lbl7antes;
    private javax.swing.JLabel _lbl7antes1;
    private javax.swing.JLabel _lbl7antes2;
    private javax.swing.JLabel _lblDespues8;
    private javax.swing.JLabel _lblDespues9;
    private javax.swing.JLabel _lblPrimerTiro;
    private javax.swing.JLabel _lblTituloMontecarlo;
    private javax.swing.JScrollPane _scpMontecarlo;
    public javax.swing.JTable _tblMontecarlo;
    private javax.swing.JTextField _txt10PrimerTiro;
    private javax.swing.JTextField _txt10SegundoTiro;
    private javax.swing.JTextField _txtCantSim;
    private javax.swing.JTextField _txtDesde;
    private javax.swing.JTextField _txtHasta;
    private javax.swing.JTextField _txtRondas;
    private javax.swing.JTextField _txtValorSuperar;
    private javax.swing.JButton btn_mostrarPtos;
    private javax.swing.JButton cargarPorDefecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblDespues10;
    private javax.swing.JLabel lblDespues9;
    private javax.swing.JTextField resultado_txt;
    private javax.swing.JTabbedPane scpSimulacion;
    public javax.swing.JTable tblDespues3;
    public javax.swing.JTable tblDespues4;
    public javax.swing.JTable tblDespues5;
    public javax.swing.JTable tblDespues6;
    public javax.swing.JTable tblDespues7;
    public javax.swing.JTable tblDespues8;
    public javax.swing.JTable tblDespues9;
    public javax.swing.JTable tblPrimerTiro;
    // End of variables declaration//GEN-END:variables

    private void limpiarTablas() {
        listaTablas.stream().map((tabla) -> (DefaultTableModel) tabla.getModel()).forEach((modelo) -> {
            for(int i = 0; i < modelo.getRowCount(); i++)
            {
                modelo.setValueAt(null, i, COL_PROB);
                modelo.setValueAt(null, i, COL_P_ACUM);
            }
        });
    }

    private void crearListaDeTablas() {
        listaTablas.add(tblPrimerTiro);
        listaTablas.add(tblDespues3);
        listaTablas.add(tblDespues4);
        listaTablas.add(tblDespues5);
        listaTablas.add(tblDespues6);
        listaTablas.add(tblDespues7);
        listaTablas.add(tblDespues8);
        listaTablas.add(tblDespues9);
    }

    private void setCheck() throws InputException {
        float probAc = 0;
        
            for (int i = 0; i < tblPrimerTiro.getRowCount(); i++) 
            {
                if (tblPrimerTiro.getValueAt(i, 1) != null && tblPrimerTiro.getValueAt(i, 1) instanceof Float)
                {
                    probAc += (float)tblPrimerTiro.getValueAt(i, 1);
                    tblPrimerTiro.setValueAt((float)probAc, i, 2);
                }
                else
                {
                    throw new InputException("Probabilidad Invalida en tabla Primer Tiro");
                }
            }
            if (probAc != 1)
            {
                throw new InputException("La probabilidad acumulada debe ser igual a 1 en la tabla Primer Tiro");
            }
            
            probAc = 0;
            for (int i = 0; i < tblDespues3.getRowCount(); i++) 
            {
                if (tblDespues3.getValueAt(i, 1) != null && tblDespues3.getValueAt(i, 1) instanceof Float)
                {
                    probAc += (float)tblDespues3.getValueAt(i, 1);
                    tblDespues3.setValueAt((float)probAc, i, 2);
                }
                else
                {
                    throw new InputException("Probabilidad Invalida en tabla si se tiraron 7");
                }
            }
            if (probAc != 1)
            {
                throw new InputException("La probabilidad acumulada debe ser igual a 1 en la tabla si se tiraron 3");
            }
            
            probAc = 0;
            for (int i = 0; i < tblDespues4.getRowCount(); i++) 
            {
                if (tblDespues4.getValueAt(i, 1) != null && tblDespues4.getValueAt(i, 1) instanceof Float)
                {
                    probAc += (float)tblDespues4.getValueAt(i, 1);
                    tblDespues4.setValueAt((float)probAc, i, 2);
                }
                else
                {
                    throw new InputException("Probabilidad Invalida en tabla si se tiraron 4");
                }
            }
            if (probAc != 1)
            {
                throw new InputException("La probabilidad acumulada debe ser igual a 1 en la tabla si se tiraron 4");
            }
            
            probAc = 0;
            for (int i = 0; i < tblDespues5.getRowCount(); i++) 
            {
                if (tblDespues5.getValueAt(i, 1) != null && tblDespues5.getValueAt(i, 1) instanceof Float)
                {
                    probAc += (float)tblDespues5.getValueAt(i, 1);
                    tblDespues5.setValueAt((float)probAc, i, 2);
                }
                else
                {
                    throw new InputException("Probabilidad Invalida en tabla si se tiraron 5");
                }
            }
            if (probAc != 1)
            {
                throw new InputException("La probabilidad acumulada debe ser igual a 1 en la tabla si se tiraron 5");
            }
            
            probAc = 0;
            for (int i = 0; i < tblDespues6.getRowCount(); i++) 
            {
                if (tblDespues6.getValueAt(i, 1) != null && tblDespues6.getValueAt(i, 1) instanceof Float)
                {
                    probAc += (float)tblDespues6.getValueAt(i, 1);
                    tblDespues6.setValueAt((float)probAc, i, 2);
                }
                else
                {
                    throw new InputException("Probabilidad Invalida en tabla si se tiraron 6");
                }
            }
            if (probAc != 1)
            {
                throw new InputException("La probabilidad acumulada debe ser igual a 1 en la tabla si se tiraron 6");
            }
            
            probAc = 0;
            for (int i = 0; i < tblDespues7.getRowCount(); i++) 
            {
                if (tblDespues7.getValueAt(i, 1) != null && tblDespues7.getValueAt(i, 1) instanceof Float)
                {
                    probAc += (float)tblDespues7.getValueAt(i, 1);
                    tblDespues7.setValueAt((float)probAc, i, 2);
                }
                else
                {
                    throw new InputException("Probabilidad Invalida en tabla si se tiraron 7");
                }
            }
            if (probAc != 1)
            {
                throw new InputException("La probabilidad acumulada debe ser igual a 1 en la tabla si se tiraron 7");
            }
            
            probAc = 0;
            for (int i = 0; i < tblDespues8.getRowCount(); i++) 
            {
                if (tblDespues8.getValueAt(i, 1) != null && tblDespues8.getValueAt(i, 1) instanceof Float)
                {
                    probAc += (float)tblDespues8.getValueAt(i, 1);
                    tblDespues8.setValueAt((float)probAc, i, 2);
                }
                else
                {
                    throw new InputException("Probabilidad Invalida en tabla si se tiraron 8");
                }
            }
            if (probAc != 1)
            {
                throw new InputException("La probabilidad acumulada debe ser igual a 1 en la tabla si se tiraron 8");
            }
            
            probAc = 0;
            for (int i = 0; i < tblDespues9.getRowCount(); i++) 
            {
                if (tblDespues9.getValueAt(i, 1) != null && tblDespues9.getValueAt(i, 1) instanceof Float)
                {
                    probAc += (float)tblDespues9.getValueAt(i, 1);
                    tblDespues9.setValueAt((float)probAc, i, 2);
                }
                else
                {
                    throw new InputException("Probabilidad Invalida en tabla si se tiraron 9");
                }
            }
            if (probAc != 1)
            {
                throw new InputException("La probabilidad acumulada debe ser igual a 1 en la tabla si se tiraron 9");
            }
            if (_txtRondas.getText() == null || "".equals(_txtRondas.getText()))
            {
                throw new InputException("Ingrese rondas");
            }
            if (_txt10PrimerTiro.getText() == null || "".equals(_txt10PrimerTiro.getText()))
            {
                throw new InputException("Ingrese puntos de tirar 10 pinos primer tiro");
            }
            if (_txt10SegundoTiro.getText() == null || "".equals(_txt10SegundoTiro.getText()))
            {
                throw new InputException("Ingrese puntos de tirar 10 pinos segundo tiro");
            }
            if (_txtValorSuperar.getText() == null || "".equals(_txtValorSuperar.getText()))
            {
                throw new InputException("Ingrese puntos a superar");
            }
            setEspecificos(Integer.parseInt(_txtRondas.getText()), Integer.parseInt(_txt10PrimerTiro.getText()), Integer.parseInt(_txt10SegundoTiro.getText()), Integer.parseInt(_txtValorSuperar.getText()));
            valuesSet = true;
    }

    private void prepararValoresPorDefault() {
        listaProbDefault.add(0.04f);
        listaProbDefault.add(0.06f);
        listaProbDefault.add(0.08f);
        listaProbDefault.add(0.11f);
        listaProbDefault.add(0.14f);
        listaProbDefault.add(0.17f);
        listaProbDefault.add(0.23f);
        listaProbDefault.add(0.17f);
        
        listaProbDefault.add(0.03f);
        listaProbDefault.add(0.07f);
        listaProbDefault.add(0.10f);
        listaProbDefault.add(0.15f);
        listaProbDefault.add(0.20f);
        listaProbDefault.add(0.25f);
        listaProbDefault.add(0.10f);
        listaProbDefault.add(0.10f);
        
        listaProbDefault.add(0.08f);
        listaProbDefault.add(0.09f);
        listaProbDefault.add(0.11f);
        listaProbDefault.add(0.15f);
        listaProbDefault.add(0.20f);
        listaProbDefault.add(0.20f);
        listaProbDefault.add(0.17f);
        
        listaProbDefault.add(0.03f);
        listaProbDefault.add(0.07f);
        listaProbDefault.add(0.10f);
        listaProbDefault.add(0.20f);
        listaProbDefault.add(0.40f);
        listaProbDefault.add(0.20f);
        
        listaProbDefault.add(0.00f);
        listaProbDefault.add(0.04f);
        listaProbDefault.add(0.16f);
        listaProbDefault.add(0.50f);
        listaProbDefault.add(0.30f);
        
        listaProbDefault.add(0.02f);
        listaProbDefault.add(0.10f);
        listaProbDefault.add(0.45f);
        listaProbDefault.add(0.43f);
        
        listaProbDefault.add(0.04f);
        listaProbDefault.add(0.20f);
        listaProbDefault.add(0.76f);
        
        listaProbDefault.add(0.06f);
        listaProbDefault.add(0.94f);
        
        //Valor 10 pinos en 1r tiro: 20
        _10primerTiroDefault = 20;
        //Valor 10 pinos en 2o tiro: 15
        _10seguntoTiroDefault = 15;
        //Rondas a simular: 10
        _rondasDefault = 10;
        //Superar puntaje: 120
        _valorSuperarDefault = 120;
    }

    private void popularTablasPorDefecto() {
        int indiceDefault = 0;
        for (JTable tabla: listaTablas)
        {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            for (int i = 0; i < modelo.getRowCount(); i++)
            {
                modelo.setValueAt(listaProbDefault.get(indiceDefault), i, COL_PROB);
                indiceDefault++;
            }
        }
    }

    private void popularCamposRequeridosPorDefecto() {
        _txt10PrimerTiro.setText("" + _10primerTiroDefault);
        _txt10SegundoTiro.setText("" + _10seguntoTiroDefault);
        _txtRondas.setText("" + _rondasDefault);
        _txtValorSuperar.setText("" + _valorSuperarDefault);
        _txtCantSim.setText("" + 100);
        _txtDesde.setText("" + 0);
        _txtHasta.setText("" + 10);
    }
}
